name: "Rylan Schaeffer's Blog"
author:
  name: "Rylan Schaeffer"
  email: "rylanschaeffer@gmail.com"
  twitter: "RylanSchaeffer"
gems:
  - jekyll-feed

title: Rylan Schaeffer
description: "'We do it because we are compelled.'"
logo: index/profile_pic.jpg
show_downloads: false
google_analytics: UA-94033137-1
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
collections_dir: collections
collections:
  blog_posts:
    output: true
  blog_drafts:
    output: true
  own_research:
    output: true
  kernel_papers:
    output: true
  kernel_papers_drafts:
    output: false

